### ISSUE TITLE
HSSM v0.1.4 import error

### ISSUE THREAD

**Issue by YuanboBQ** [lnccbrown/HSSM#277]
Hi,
I attempted to update the HSSM to version0.1.4. However, when i import the package(v0.1.4), there is some errors as follow:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yuanbo/miniforge3/lib/python3.9/site-packages/hssm/__init__.py", line 6, in <module>
    from .config import ModelConfig
  File "/Users/yuanbo/miniforge3/lib/python3.9/site-packages/hssm/config.py", line 10, in <module>
    from .defaults import LogLik, LoglikKind, SupportedModels, default_model_config
  File "/Users/yuanbo/miniforge3/lib/python3.9/site-packages/hssm/defaults.py", line 10, in <module>
    from .likelihoods.analytical import (
  File "/Users/yuanbo/miniforge3/lib/python3.9/site-packages/hssm/likelihoods/__init__.py", line 4, in <module>
    from .blackbox import logp_ddm_bbox, logp_ddm_sdv_bbox, logp_full_ddm
  File "/Users/yuanbo/miniforge3/lib/python3.9/site-packages/hssm/likelihoods/blackbox.py", line 7, in <module>
    from .hddm_wfpt import wfpt
  File "/Users/yuanbo/miniforge3/lib/python3.9/site-packages/hssm/likelihoods/hddm_wfpt/__init__.py", line 4, in <module>
    from . import wfpt  # noqa: F401
ImportError: cannot import name 'wfpt' from partially initialized module 'hssm.likelihoods.hddm_wfpt' (most likely due to a circular import) (/Users/yuanbo/miniforge3/lib/python3.9/site-packages/hssm/likelihoods/hddm_wfpt/__init__.py)
```
How to fix it, thanks!

**Comment by digicosmos86** [comment]
Hi,

Unfortunately, we are experiencing some issues with v0.1.4 release and we have since pulled 0.1.4 from PyPI. We are working on a fix right now and will hopefully fix it today. In the meantime, please use v0.1.3. Sorry for the inconvenience!

**Comment by digicosmos86** [comment]
We have fixed everything in 0.1.5. Please give it a try :)

**Comment by YuanboBQ** [comment]
Hi Pual,

Thanks. I have update the HSSM to version0.1.5 and import the package without error. However, I found that using this version there is still problem when handling complex models. For example, I used the following code. It works fine using version0.1.3, but it results in very high values for r_hat when using version0.1.5.

```
hierarchical_ddm_model_reg_v = hssm.HSSM(
    model = "ddm",
    data = cav_data,
    loglik_kind = "approx_differentiable", #"analytical"    
    include = [
        {
            "name": "v",
            "formula": "v ~ 1 + (1 |subj_idx)",
            #"formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
        },
        {
            "name": "z",
            "formula": "z ~ 1 + (1|subj_idx)",
            #"formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
            #"link": "logit",
        },     
        {
            "name": "a",
            "formula": "a ~ 1 + (1|subj_idx)",
            #"formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
            #"link": "log",
        },
        {
            "name": "t",
            "formula": "t ~ 1 + (1|subj_idx)",
            #"formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
        },                         
    ],     
)

```
I also test this version using my dataset, there is aslo problem when handling complex models.

**Comment by AlexanderFengler** [comment]
Hi YuanBo,

could you give us the whole code you used or include a screenshot of the relevant summary stats / traces? 

This is very likely because something is still going wrong when initializing the chains. We have to be a bit more defensive on that front and increase code coverage as well. 

We will work on this as highest priority in the coming days. Thank you for reporting this.

Best,
Alex

**Comment by AlexanderFengler** [comment]
As a sidenote, 
if you pick log link for 'a' and 't' as well as logit link for 'z', do you still have the same issue?

**Comment by YuanboBQ** [comment]
Hi Alex, Here is the code I used with the cav_data dataset, and a screenshot of the relevant summary stats / traces.

```
# Define a basic hierarchical model with trial-level covariates
loglik_kind_hierarchical_ddm_model = hssm.HSSM(
    model = "ddm",
    loglik_kind = "approx_differentiable", #"analytical"
    data = cav_data,
    include = [
        {
            "name": "v",
            "formula": "v ~ 1 + (1|subj_idx)",
            #"formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
        },
        {
            "name": "a",     
            "formula": "a ~ 1 + (1|subj_idx)",
            #"formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
        },              
        {
            "name": "z",
            "formula": "z ~ 1 + (1|subj_idx)",
            #"formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
        },     
    ],
)

print(loglik_kind_hierarchical_ddm_model)

```

```
%%time
# Sample from the posterior for this model
loglik_kind_hierarchical_ddm_model.sample(sampler = "nuts_numpyro", 
                              chains = 2,  # how many chains to run
                              cores = 8,  # how many cores to use
                              draws = 1000,  # number of draws from the markov chain
                              tune = 500,  # number of burn-in samples
                              )
```

<img width="1087" alt="截屏2023-09-12 08 15 44" src="https://github.com/lnccbrown/HSSM/assets/2658686/e32d17c8-a385-431a-b88d-ff2f49e632c9">

```
az.summary(loglik_kind_hierarchical_ddm_model.traces, var_names = ['~z', '~a'])
```
<img width="850" alt="截屏2023-09-12 08 15 08" src="https://github.com/lnccbrown/HSSM/assets/2658686/5bcc78a4-0fb9-49cb-9592-7ec7938b0beb">

By the way, it seems the runtime is a little longer when using v0.1.5 than v0.1.3. The following is the information about my operating environment.

```
Python implementation: CPython
Python version       : 3.9.9
IPython version      : 8.14.0

pytensor: 2.12.3
aeppl   : not installed

numpy     : 1.25.1
pytensor  : 2.12.3
pandas    : 2.0.3
hssm      : 0.1.5
arviz     : 0.14.0
seaborn   : 0.12.2
matplotlib: 3.7.2
bambi     : 0.12.0

Watermark: 2.4.3
```

**Comment by AlexanderFengler** [comment]
Thank you for getting back, we will look into it asap.

**Comment by AlexanderFengler** [comment]
Hey @YuanboBQ, 

we did some investigation on this and it turns out that sampler initialization seems to be the main problem here. The initialization defaults of pymc / bambi don't take into account enough specifics of our models and therefore propose parameter values at the beginning of sampling that are non-sensical. When the chain get's initialized like that it very often can recover (find an actual mode to properly sample from). 

We can get your example working without issues by manually setting the initialization, but need a bit more time to get a general solution ready. 

Thank you for alerting us to the issue, the next version of HSSM will be much more robust as a consequence. 

Best,
Alex
